---

- name: "download wordpress"
  get_url:
    url: "https://wordpress.org/latest.tar.gz" 
    dest: "/tmp/wordpress.tar.gz"
  become: yes  

- name: "unzip wordpress"
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/"
    remote_src: yes
  become: yes

- name: "copy wordpress config-sample file"
  copy:
    src: "{{ wp_install_dir }}/wp-config-sample.php"
    dest: "{{ wp_install_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: "update wordpress config file with MySQL vars"
  template:
    src: "templates/wp-config.php.j2"
    dest: "/var/www/wordpress/wp-config.php"
    remote_src: no
  become: yes

# - name: "update wordpress config file with MySQL vars"
#   replace:
#     path: "{{ wp_install_dir }}/wp-config.php"
#     regexp: "{{ item.regexp }}"
#     replace: "{{ item.value }}"
#   with_items: 
#   - { regexp: 'database_name_here', value: "{{ wp_db_name }}" } 
#   - { regexp: 'username_here', value: "{{ wp_db_username }}" }
#   - { regexp: 'password_here', value: "{{ wp_user_password }}" }
#   - { regexp: 'localhost', value: "{{ wp_db_ip }}" }         
#   become: yes 

- name: "points apache2 to server wordpress at port 80"
  template:
    src: "templates/000-default.conf.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"
    remote_src: no
  become: yes
  notify: 
    - restart apache  